### ISSUE TITLE
How to receive SSE with POST method?

### ISSUE THREAD

**Issue by imbytecat** [BinarSkugga/insomnia-plugin-skugga-sse#1]
Hello, I really like Insomnia and thank you for developing this extension! Recently, I've been debugging OpenAI.com's GPT API, but they use POST for SSE requests. I know that GET should be used by default, but using POST is actually a very common situation. Could you please advise me on how to make this plugin work? I'm a JS beginner, so it would be really great if you could help! Right now, I'm forced to use the bulky Postman to complete API debugging.

**Comment by BinarSkugga** [comment]
The SSE standard does not allow for POST. Since I use the EventSource class which follows this standard, you can't use this to have your SSE work through POST. Source: https://stackoverflow.com/a/34285526

**Comment by Morgan-6Freedom** [comment]
This is a POST Request with SSE when stream=true.
https://platform.openai.com/docs/api-reference/chat/create

**Comment by BinarSkugga** [comment]
Yes but this is not standard. Because I use vanilla JS [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events), I do not control the HTTP method. Until this is supported by JS, not much I can do. I won't reimplement the EventSource class.
