### ISSUE TITLE
Method "SSE" not allowed

### ISSUE THREAD

**Issue by merc1er** [BinarSkugga/insomnia-plugin-skugga-sse#3]
When specifying the `SSE` method as instructed, it does actually modify the request method to SSE, which is not a default HTTP method.

Can the plugin be triggered on valid default HTTP methods (e.g. `GET`)?

![sse](https://github.com/BinarSkugga/insomnia-plugin-skugga-sse/assets/21960643/eb72efc8-d864-48d1-99c6-667e6c66c874)

**Comment by BinarSkugga** [comment]
It should send a GET behind the scene, the SSE method is only to detect your intent. I'll investiguate.

**Comment by merc1er** [comment]
It looks like it sends an SSE request, then a GET. But the first request is treated first.

**Comment by BinarSkugga** [comment]
Maybe I could detect intent with a header, will look into it. Thanks !

**Comment by BinarSkugga** [comment]
Can't seem to prevent the initial request from being sent but it will now trigger on the `x-sse` header being truthy. Tell me if that fixes your issue.

![image](https://github.com/BinarSkugga/insomnia-plugin-skugga-sse/assets/7575628/d7c8d94c-52e8-4d32-bd4a-082e3a573b73)

Published on npm v0.2.1

**Comment by merc1er** [comment]
So, it looks like you renamed the `main.js` file. 

For this reason I am unable to install the plugin using Insomnia:
![sse](https://github.com/BinarSkugga/insomnia-plugin-skugga-sse/assets/21960643/ff8fb07d-939e-42a3-87af-2508724e4703)

Traceback:
```
Error: ENOENT: no such file or directory, open '<...>/Insomnia/plugins/insomnia-plugin-skugga-sse/main.js'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:462:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:18)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
````

**Comment by merc1er** [comment]
I just renamed `app.js` -> `main.js` and it kind of worked. It sends a GET request without any query strings and headers, then sends the actual complete request and works.

**Comment by BinarSkugga** [comment]
> So, it looks like you renamed the `main.js` file.
> 
> For this reason I am unable to install the plugin using Insomnia: ![sse](https://user-images.githubusercontent.com/21960643/246706838-ff8fb07d-939e-42a3-87af-2508724e4703.png)
> 
> Traceback:
> 
> ```
> Error: ENOENT: no such file or directory, open '<...>/Insomnia/plugins/insomnia-plugin-skugga-sse/main.js'
>     at Object.openSync (node:fs:594:3)
>     at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
>     at Object.readFileSync (node:fs:462:35)
>     at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1159:18)
>     at Module.load (node:internal/modules/cjs/loader:1011:32)
>     at Module._load (node:internal/modules/cjs/loader:846:12)
>     at f._load (node:electron/js2c/asar_bundle:2:13328)
>     at o._load (node:electron/js2c/renderer_init:2:3109)
>     at Module.require (node:internal/modules/cjs/loader:1035:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
> ```

Yes, just delete the plugin from your folder, reboot insomnia and reinstall. My bad !
